### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by Onex101** [Onex101/home-me#4]
Agent or House Owner

**Comment by RuanMatthee** [comment]
I think fleshing out the exact scenario (I don't like the word 'problem' due to the negative connotations, so maybe we can use something else, like 'scenario'? 😃 ) we want to support is step #1. 

I.m.o, Tinder's chat:

1. Listing all of someone's personality traits, interests, manner of speaking and being isn't feasible, so this could be done through chat. Meaning, a whole bunch of information and chemistry was discovered through with the chat.
2. The human concept of connection to someone had to be created before actually meeting someone.
3. For those never planning on actually meeting someone soon, just for socializing.

With property, a lot more is at stake. We'll have NB facts listed on something like #3 and also viewing booking feature.
At the moment, I cannot find a solid use case for having a chat. If it was me, I want to see clear photos, features of the flat, pricing and then view a booking to see it for myself.

If one wants to contact the agent, having another channel for communication is extra effort for the agents as well as more complexity.

@Onex101 Wat dink jy?

**Comment by Onex101** [comment]
That's a good point. From experience I've had to contact agents but then we use email/ whatsapp. So utilizing the premise of using external communication channels might benefit.
However in da future we might want to look at because some might want a business account and not have thier Whatsapp feel bloated but it can be put on the back burner for now.
